freebsd_instance:
  image_family: freebsd-12-2

freebsd_task:
  env:
    matrix:
      - OCAML_VERSION: 4.13.1
      - OCAML_VERSION: 4.14.1

  pkg_install_script: pkg install -y ocaml-opam gmp gmake pkgconf bash

  ocaml_script:
    - opam init -a --comp=$OCAML_VERSION
    - opam env

  pin_packages_script:
    - opam install -y --deps-only -t ./mirage-crypto.opam ./mirage-crypto-rng.opam ./mirage-crypto-rng-lwt.opam ./mirage-crypto-rng-mirage.opam ./mirage-crypto-rng-async.opam ./mirage-crypto-ec.opam ./mirage-crypto-pk.opam

  test_script: opam exec -- dune runtest -p mirage-crypto,mirage-crypto-rng,mirage-crypto-rng-lwt,mirage-crypto-rng-mirage,mirage-crypto-pk,mirage-crypto-ec,mirage-crypto-rng-async

  test_mirage_script: eval `opam env` && ./.test-mirage.sh

freebsd_eio_task:
  pkg_install_script: pkg install -y ocaml-opam gmake pkgconf bash

  ocaml_script:
    - opam init -a --comp=5.0.0
    - opam env

  pin_packages_script:
    - opam install -y --deps-only -t ./mirage-crypto.opam ./mirage-crypto-rng.opam ./mirage-crypto-rng-eio.opam

  test_script: opam exec -- dune runtest -p mirage-crypto,mirage-crypto-rng,mirage-crypto-rng-eio
