#!/bin/sh -e

OS=${OS:-unix}
OCAMLBUILD="ocamlbuild -use-ocamlfind -syntax camlp4o"
PKG="lwt,lwt.syntax,cstruct,mirage-types,mirage-xen"
CFLAGS="-ccopt,-mrdrnd,-ccopt,-mrdseed"

TARGET="${OS}/mirage-entropy.cma ${OS}/mirage-entropy.cmxa ${OS}/mirage-entropy.cmxs"

case "${OS}" in
  xen)
    ${OCAMLBUILD} \
      -pkgs ${PKG} \
      -cflags '-ccopt,-mrdrnd,-ccopt,-mrdseed' \
      -tag-line "<xen/mirage-entropy.{cma,cmxa}>: use_libmirage-entropy_xen_stubs" \
      ${OS}/libmirage-entropy_xen_stubs.a \
      ${TARGET}
    ;;
  unix)
    ${OCAMLBUILD} ${PKG} -pkgs lwt.unix,cstruct.lwt ${TARGET}
    ;;
esac

B=_build/${OS}
if [ "$1" = "true" ]; then
  ocamlfind remove mirage-entropy-${OS} || true
  ocamlfind install mirage-entropy-${OS} ${OS}/META \
    ${B}/*.{cmi,cmo,cmx,a,cma,cmxa,cmxs}
#     $B/entropy_${OS}.cmo $B/entropy_${OS}.cmi $B/mirage-entropy.cma \
#     $B/mirage-entropy.a $B/entropy_${OS}.cmx $B/mirage-entropy.cmxa $B/mirage-entropy.cmxs
fi
