name: Crypto

on: [push, pull_request]

jobs:
  cross_compile:
    name: Cross compile

    strategy:
      fail-fast: false
      matrix:
        target: [android.arm64, linux.musl.arm64]
        ocaml-version: ["~4.10.1000"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create esy wrapper
        run: |
          echo '{
            "name": "cross-compile",
            "dependencies": {
              "ocaml": "${{ matrix.ocaml-version }}",
              "mirage-crypto": "./mirage-crypto.opam",
              "mirage-crypto-ec": "./mirage-crypto-ec.opam",
              "mirage-crypto-pk": "./mirage-crypto-pk.opam",
              "mirage-crypto-rng": "./mirage-crypto-rng.opam",
              "mirage-crypto-rng-mirage": "./mirage-crypto-rng-mirage.opam",
              "generate": "github:EduardoRFS/reason-mobile:generate.json#5e2685f419ac88aad3d4d37932d62620c90b40d8"
            },
            "resolutions": {
              "@opam/mtime": "github:dune-universe/mtime:mtime.opam#9584b66cecc891208b31cec4628dd412b8cffe75",
              "@opam/zarith": "github:dune-universe/Zarith:zarith.opam#c62b045106fafa407874053bdd79273a8f591352",
              "@opam/num": "github:dune-universe/num:num.opam#bdb2d7653e927e142b701b51d89f393471279713"
            }
          }' > esy.json

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install esy
        run: npm install -g esy
      - name: Create cross compile toolchain lock
        run: esy solve
      - uses: esy/github-action@v1
        with:
          cache-key: ${{ matrix.target }}-${{ hashFiles('esy.lock/index.json') }}

      - name: Create ${{ matrix.target }} wrapper
        run: esy generate ${{ matrix.target }}

      - name: Install ${{ matrix.target }} dependencies
        run: esy @${{ matrix.target }} install

      - name: Build ${{ matrix.target }}
        run: esy @${{ matrix.target }} build
